name: Build release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: philipparndt/get-release-number@v3
        id: next
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseType: ${{ github.event.inputs.releaseType }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Test
        working-directory: app
        run: go test ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.next.outputs.version }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            pharndt/mielemqtt:latest
            pharndt/mielemqtt:${{env.RELEASE_VERSION}}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          tag: ${{env.RELEASE_VERSION}}
          name: ${{env.RELEASE_VERSION}}
          body: |
            Docker tag: `pharndt/mielemqtt:${{env.RELEASE_VERSION}}`

            Changes in this Release
              - Go rewrite
              - ...

          draft: false
          prerelease: false
