name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        MIELE_CLIENT_ID: MIELE_CLIENT_ID 
        MIELE_CLIENT_SECRET: MIELE_CLIENT_SECRET 
        MIELE_PASSWORD: MIELE_PASSWORD 
        MIELE_USERNAME: MIELE_USERNAME 
    - name: Build with Maven
      run: mvn -B package --file src/pom.xml
      env:
        MIELE_CLIENT_ID: ${{ secrets.MIELE_CLIENT_ID }}
        MIELE_CLIENT_SECRET: ${{ secrets.MIELE_CLIENT_SECRET }}
        MIELE_PASSWORD: ${{ secrets.MIELE_PASSWORD }}
        MIELE_USERNAME: ${{ secrets.MIELE_USERNAME }}
